import React, { useEffect, useState } from "react";
import { Sparkles } from "lucide-react";
import { Product } from "../types";
import { recommendationService } from "../services/recommendationService";
import ProductCard from "../components/ProductCard";
import Loader from "../components/Loader";

const Recommendations: React.FC = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const [personalized, setPersonalized] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    recommendationService
      .getForMe()
      .then(({ products, personalized }) => {
        setProducts(products);
        setPersonalized(personalized);
      })
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
          <Sparkles size={22} className="text-brand-600" />
          {personalized ? "Recommended For You" : "Recommended Picks"}
        </h1>
        <p className="text-sm text-slate-500 mt-1 max-w-xl">
          {personalized
            ? "Generated by IBM Watson Natural Language Understanding, based on products you've recently viewed and purchased."
            : "Sign in and browse a few products — IBM Watson will start tailoring recommendations to you."}
        </p>
      </div>

      {loading ? (
        <Loader />
      ) : products.length === 0 ? (
        <div className="text-center py-20 text-slate-500">No recommendations yet — check back after browsing a bit!</div>
      ) : (
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-5">
          {products.map((p) => (
            <ProductCard key={p._id} product={p} />
          ))}
        </div>
      )}
    </div>
  );
};

export default Recommendations;
